// time.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: time.proto

package time

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCurrentTimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentTimeRequest) Reset() {
	*x = GetCurrentTimeRequest{}
	mi := &file_time_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentTimeRequest) ProtoMessage() {}

func (x *GetCurrentTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_time_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentTimeRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentTimeRequest) Descriptor() ([]byte, []int) {
	return file_time_proto_rawDescGZIP(), []int{0}
}

type GetCurrentTimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentTimeResponse) Reset() {
	*x = GetCurrentTimeResponse{}
	mi := &file_time_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentTimeResponse) ProtoMessage() {}

func (x *GetCurrentTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_time_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentTimeResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentTimeResponse) Descriptor() ([]byte, []int) {
	return file_time_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurrentTimeResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

var File_time_proto protoreflect.FileDescriptor

const file_time_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"time.proto\x12\x10grpctest.time.v1\"\x17\n" +
	"\x15GetCurrentTimeRequest\",\n" +
	"\x16GetCurrentTimeResponse\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date2\xdf\x01\n" +
	"\vTimeService\x12c\n" +
	"\x0eGetCurrentTime\x12'.grpctest.time.v1.GetCurrentTimeRequest\x1a(.grpctest.time.v1.GetCurrentTimeResponse\x12k\n" +
	"\x14GetCurrentTimeStream\x12'.grpctest.time.v1.GetCurrentTimeRequest\x1a(.grpctest.time.v1.GetCurrentTimeResponse0\x01B\n" +
	"Z\bpkg/timeb\x06proto3"

var (
	file_time_proto_rawDescOnce sync.Once
	file_time_proto_rawDescData []byte
)

func file_time_proto_rawDescGZIP() []byte {
	file_time_proto_rawDescOnce.Do(func() {
		file_time_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_time_proto_rawDesc), len(file_time_proto_rawDesc)))
	})
	return file_time_proto_rawDescData
}

var file_time_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_time_proto_goTypes = []any{
	(*GetCurrentTimeRequest)(nil),  // 0: grpctest.time.v1.GetCurrentTimeRequest
	(*GetCurrentTimeResponse)(nil), // 1: grpctest.time.v1.GetCurrentTimeResponse
}
var file_time_proto_depIdxs = []int32{
	0, // 0: grpctest.time.v1.TimeService.GetCurrentTime:input_type -> grpctest.time.v1.GetCurrentTimeRequest
	0, // 1: grpctest.time.v1.TimeService.GetCurrentTimeStream:input_type -> grpctest.time.v1.GetCurrentTimeRequest
	1, // 2: grpctest.time.v1.TimeService.GetCurrentTime:output_type -> grpctest.time.v1.GetCurrentTimeResponse
	1, // 3: grpctest.time.v1.TimeService.GetCurrentTimeStream:output_type -> grpctest.time.v1.GetCurrentTimeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_time_proto_init() }
func file_time_proto_init() {
	if File_time_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_time_proto_rawDesc), len(file_time_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_time_proto_goTypes,
		DependencyIndexes: file_time_proto_depIdxs,
		MessageInfos:      file_time_proto_msgTypes,
	}.Build()
	File_time_proto = out.File
	file_time_proto_goTypes = nil
	file_time_proto_depIdxs = nil
}
